version: '3.8'

services:

  web:
    build: .
    container_name: service_api
    command: python manage.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


